### ISSUE TITLE
Error when trying to download data

### ISSUE THREAD

**Issue by EHJ-52n** [EHJ-52n/jrc-aqsens-download#2]
@michelgerboles 
When executing the latest version, I receive the following error message:

```
[SETTIME] ERROR, no SetTime server config file for the AirSensEUR box. 
The App is going to crash. This AirSensEUR cannot be selected.
Error in Config$sens2ref.shield : 
  $ operator is invalid for atomic vectors
```

See [error.log](https://github.com/EHJ-52n/jrc-aqsens-download/files/4186401/error.log) for the full log of my run executed via:

```R
> sink("error.log", split = TRUE)
> source("influxdb_download.R")
```

**Comment by michelgerboles** [comment]
Hi Eike,

Are you using the box 40458D when you get this message?

Best regards,

Michel

**Comment by EHJ-52n** [comment]
I am using the `JRC_16` station located in the `ASE_boxes/JRC_16` folder. By the way, I could not find the id `40458D` in any file in the repository.

**Comment by michelgerboles** [comment]
40458D which one of the box of AQSens should be at

https://github.com/ec-jrc/airsenseur-calibration/tree/master/ASE_Boxes/40458D


It would be good to switch to this box since we are going to use later for the deployment.


Yesterday I updated much of the scripts at airsenseur-calibration

including Function4ASE.R that constains the SETTIME function.

Anyhow I did not get the error on SETTIME, maybe it is related to using JRC16.


Let's speak this afternoon.

Michel

**Comment by EHJ-52n** [comment]
I have updated the `influxdb_download.R` to download at the beginning the latest versions of:

- `global.R`
- `151016 Sensor_Toolbox.R`
- `Functions4ASE.R`

and replaced the JRC_16 box as you recommend.

- fea096e7672db139f84f547a0129fa16ab81ad8b
- dba212d5fc664f1b96efbef74a308cd2b3fef9bd

The result is still the same ([complete log](https://github.com/EHJ-52n/jrc-aqsens-download/files/4191640/error.log)):
```
SETTIME] ERROR, no SetTime server config file for the AirSensEUR box. 
The App is going to crash. This AirSensEUR cannot be selected.
Error in Config$sens2ref.shield : 
  $ operator is invalid for atomic vectors
```

I agree to clarify this this afternoon.

**Comment by michelgerboles** [comment]
This error message is because you are missing this file

https://github.com/ec-jrc/airsenseur-calibration/blob/master/ASE_Boxes/40458D/Configuration/40458D_SETTIME.cfg


in the "Configuration" directory

**Comment by michelgerboles** [comment]
By the time be sure to have all the new files in ./Configuration and ./General_data

**Comment by EHJ-52n** [comment]
The file `40458D_SETTIME.cfg` is already [in this repository](https://github.com/EHJ-52n/jrc-aqsens-download/blob/master/ASE_boxes/40458D/Configuration/40458D_SETTIME.cfg) and the folders are the same:

```shell
 ~/jrc-aqsens-download [master]$ diff -r ASE_boxes ../airsenseur-calibration/ASE_Boxes 
 ~/jrc-aqsens-download [master]$ 
```
